"""
Django settings for EnceFAL project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from django.core.urlresolvers import reverse_lazy
from conf import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=%^*-zf1a#8@75co(akv9og(xd5d!8zgk%$ssi^z=&rrt138pa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# True => Taxes are calculated
# False => Taxes aren't calculated
TAXABLES = True

# Application definition
# The order is VERY important,
# employee must come before django.contrib.admin

INSTALLED_APPS = [
	'main',
	'employee',
	'corsheaders',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.admin',
	#'django.contrib.admin.apps.SimpleAdminConfig',
    'django.contrib.staticfiles',
	'django_nose',
]

MIDDLEWARE_CLASSES = [
	'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EnceFAL.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
			'debug': DEBUG,
            'context_processors': [
				'django.contrib.auth.context_processors.auth',
               	'django.template.context_processors.debug',
				'django.template.context_processors.i18n',
				'django.template.context_processors.media',
				'django.template.context_processors.static',
				'django.template.context_processors.tz',
      			'django.template.context_processors.request',
				'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#### MEDIA Paths ####
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_PRIVE_ROOT = os.path.join(BASE_DIR, 'media_prive')
MEDIA_URL = '/media/'

WSGI_APPLICATION = 'EnceFAL.wsgi.application'

LOGIN_REDIRECT_URL = "/employee/"
LOGIN_URL = "/employee/login/"

#### Tests config ####
TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'

NOSE_ARGS=[
	'--with-coverage'
]


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

ALLOWED_HOSTS = [ "localhost" ]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'fr-ca'

TIME_ZONE = 'America/Montreal'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 1


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

### STATIC paths ###
STATICFILES_DIRS = [
	os.path.join(BASE_DIR, 'EnceFAL', 'static'),
]
STATIC_URL = '/static/'
