# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text=b'Le format de la date est JJ/MM/AAAA')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text=b'Le format de la date est JJ/MM/AAAA')),
                ('etat', models.CharField(choices=[(b'VENT', b'En vente'), (b'VEND', b'Vendu'), (b'PERD', b'Perdu'), (b'VOLE', b'Vol\xc3\xa9'), (b'REND', b'Rendu'), (b'REMB', b'Rembours\xc3\xa9')], default=b'VENT', max_length=4, verbose_name=b'\xc3\x89tat')),
                ('prix', main.models.PriceField(decimal_places=2, default=0.0, help_text=b'Doit \xc3\xaatre entre 0 et 999.95', max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text=b'Le format de la date est JJ/MM/AAAA')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text=b'Le format de la date est JJ/MM/AAAA')),
                ('employe', models.ForeignKey(blank=True, db_column=b'employe', on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text=b'Le format de la date est JJ/MM/AAAA')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text=b'Le format de la date est JJ/MM/AAAA')),
                ('isbn', models.CharField(blank=True, help_text=b'Scannez le code ISBN', max_length=13, unique=True, verbose_name=b'ISBN du livre')),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('auteur', models.CharField(blank=True, max_length=255)),
                ('edition', models.PositiveIntegerField(blank=True, default=1, verbose_name=b'\xc3\x89dition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text=b'Le format de la date est JJ/MM/AAAA')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text=b'Le format de la date est JJ/MM/AAAA')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('date_debut', models.DateField(blank=True, help_text=b'Le format de la date est JJ/MM/AAAA', null=True, verbose_name=b'Date d\xc3\xa9but')),
                ('date_fin', models.DateField(blank=True, help_text=b'Le format de la date est JJ/MM/AAAA', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text=b'Le format de la date est JJ/MM/AAAA')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text=b'Le format de la date est JJ/MM/AAAA')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255, verbose_name=b'Pr\xc3\xa9nom')),
                ('code_permanent', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=255, verbose_name=b'T\xc3\xa9l\xc3\xa9phone')),
            ],
            options={
                'verbose_name': 'Vendeur (Vrai)',
                'verbose_name_plural': 'Vendeurs (Vrai)',
            },
        ),
        migrations.AddField(
            model_name='livre',
            name='vendeur',
            field=models.ManyToManyField(db_column=b'vendeur', related_name='livres', through='main.Exemplaire', to='main.Vendeur'),
        ),
        migrations.AddField(
            model_name='facture',
            name='session',
            field=models.ForeignKey(blank=True, db_column=b'session', on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='main.Session'),
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='facture',
            field=models.ForeignKey(blank=True, db_column=b'facture', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='main.Facture'),
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='livre',
            field=models.ForeignKey(db_column=b'livre', on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='main.Livre'),
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='vendeur',
            field=models.ForeignKey(db_column=b'vendeur', on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='main.Vendeur'),
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
            ],
            options={
                'verbose_name': 'Vendeur',
                'proxy': True,
                'verbose_name_plural': 'Vendeurs',
            },
            bases=('main.vendeur',),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('main.facture',),
        ),
    ]
