# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_facture_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='taxes',
            field=models.BooleanField(default=False, help_text=b'Cette facture prend en compte les taxes', verbose_name=b'TPS/TVQ'),
        ),
    ]
