# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_facture_taxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='taxes',
        ),
    ]
