# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_facture_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='code_carte_etudiante',
            field=models.IntegerField(default=0, help_text=b'Scannez la carte \xc3\xa9tudiante', verbose_name=b'Code carte \xc3\xa9tudiante'),
            preserve_default=False,
        ),
    ]
