# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-02 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_vendeur_code_carte_etudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='code_carte_etudiante',
            field=models.IntegerField(blank=True, help_text=b'Scannez la carte \xc3\xa9tudiante', null=True, verbose_name=b'Code carte \xc3\xa9tudiante'),
        ),
    ]
